# Generated by Django 5.2.1 on 2025-05-31 21:01

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dictionaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(default='default.pdf', upload_to=core.models.lecture_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл лекции'),
        ),
    ]
