# Generated by Django 5.2.1 on 2025-05-31 22:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lecture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='objective',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path, verbose_name='Изображение'),
        ),
    ]
