# Generated by Django 5.2.1 on 2025-06-07 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_exercise_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('is_upgraded', models.BooleanField(default=False)),
                ('last_slow_click', models.DateTimeField(blank=True, null=True)),
                ('fast_clicks_today', models.IntegerField(default=0)),
                ('last_update_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
