# Generated by Django 5.2.1 on 2025-06-07 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name': 'Профиль баллов', 'verbose_name_plural': 'Профили баллов'},
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('fast', 'Быстрое начисление'), ('slow', 'Медленное начисление')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.userpoints')),
            ],
            options={
                'verbose_name': 'История баллов',
                'verbose_name_plural': 'Истории баллов',
                'ordering': ['-date'],
            },
        ),
    ]
