# Generated by Django 5.2.1 on 2025-06-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userpoints_options_alter_userpoints_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpoints',
            options={},
        ),
    ]
