# Generated by Django 5.2.1 on 2025-06-07 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name': 'Баллы пользователя', 'verbose_name_plural': 'Баллы пользователей'},
        ),
        migrations.RenameField(
            model_name='pointhistory',
            old_name='user',
            new_name='user_points',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='points_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='type',
            field=models.CharField(choices=[('slow', 'Медленное нажатие'), ('fast', 'Быстрое нажатие'), ('upgrade', 'Улучшение'), ('chat', 'Отправка сообщения в чат')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['-timestamp'], name='core_chatme_timesta_92f539_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user'], name='core_chatme_user_id_cbf50f_idx'),
        ),
    ]
