# Generated by Django 5.2.1 on 2025-06-07 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_chatmessage_options_alter_userpoints_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='points_spent',
            field=models.IntegerField(default=0, verbose_name='Потрачено баллов'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='amount',
            field=models.IntegerField(verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='type',
            field=models.CharField(choices=[('slow', 'Медленное нажатие'), ('fast', 'Быстрое нажатие'), ('upgrade', 'Улучшение'), ('chat', 'Отправка сообщения в чат')], max_length=10, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='user_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.userpoints', verbose_name='Баллы пользователя'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='fast_clicks_today',
            field=models.IntegerField(default=0, verbose_name='Быстрых нажатий сегодня'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='is_upgraded',
            field=models.BooleanField(default=False, verbose_name='Аккаунт улучшен'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='last_slow_click',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее медленное нажатие'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='last_update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Текущие баллы'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Всего заработано баллов'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['-date'], name='core_pointh_date_733700_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['user_points'], name='core_pointh_user_po_39fc83_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['type'], name='core_pointh_type_14c49b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['last_update_date'], name='core_userpo_last_up_c1f58d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['user'], name='core_userpo_user_id_b7a0ea_idx'),
        ),
    ]
