# Generated by Django 5.2.1 on 2025-06-08 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatmessage_options_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatme_user_id_cbf50f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userpoints',
            name='core_userpo_last_up_c1f58d_idx',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='last_update_date',
        ),
        migrations.AddField(
            model_name='userpoints',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='fast_clicks_today',
            field=models.PositiveIntegerField(default=0, verbose_name='Быстрых нажатий сегодня'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='is_upgraded',
            field=models.BooleanField(default=False, verbose_name='Премиум-статус'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='last_slow_click',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний медленный клик'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущие баллы'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего заработано баллов'),
        ),
        migrations.AddIndex(
            model_name='userpoints',
            index=models.Index(fields=['last_activity'], name='core_userpo_last_ac_0d65d2_idx'),
        ),
    ]
