# Generated by Django 5.2.1 on 2025-06-08 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='pointhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История баллов', 'verbose_name_plural': 'История баллов'},
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='core_pointh_date_733700_idx',
        ),
        migrations.RenameField(
            model_name='pointhistory',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='points_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Потрачено баллов'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='type',
            field=models.CharField(choices=[('slow_click', 'Медленный клик'), ('fast_click', 'Быстрый клик'), ('spend', 'Списание'), ('chat', 'Сообщение в чате'), ('upgrade', 'Улучшение'), ('bonus', 'Бонус'), ('other', 'Другое')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user'], name='core_chatme_user_id_cbf50f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted'], name='core_chatme_is_dele_621a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['-created_at'], name='core_pointh_created_3a13e7_idx'),
        ),
    ]
