# Generated by Django 5.2.1 on 2025-06-10 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chatmessage_options_alter_pointhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='pointhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatme_is_dele_621a1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointhistory',
            name='core_pointh_type_14c49b_idx',
        ),
        migrations.AddField(
            model_name='userpoints',
            name='first_click_today',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='type',
            field=models.CharField(choices=[('slow_click', 'Медленный клик'), ('fast_click', 'Быстрый клик'), ('spend', 'Списание'), ('chat', 'Чат'), ('upgrade', 'Улучшение'), ('bonus', 'Бонус'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pointhistory',
            name='user_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.userpoints'),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='fast_clicks_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='is_upgraded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='last_slow_click',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
